### ISSUE TITLE
主界面的所有活动列表、所有社团列表、我的社团的活动列表

### ISSUE THREAD

**Issue by taoky** [Community-Member-Management-System/CMMS-Backend#14]

**Comment by kaleid-liner** [comment]
设计时，总体来说，这个页面的三个列表是位于不同的 views 中的，有前端进行请求。

对于 activity 的列表而言，请求列表时，获取哪些活动通过参数提供：

- [activity/?community=id]() 将获取该社团的活动列表，这同时也是 #10 的需求
- [activity/?only_mine]() 将只获取自己社团的活动列表。
