### ISSUE TITLE
活动的签到功能

### ISSUE THREAD

**Issue by kaleid-liner** [Community-Member-Management-System/CMMS-Backend#15]
活动签到目前至少需要实现两个选项：

- 通过验证码签到
- 管理员手动将成员添加到签到列表

详见用户故事。

**Comment by kaleid-liner** [comment]
大家对通过验证码签到的方式有什么建议吗。我按照前期讨论，目前有两个思路：

- 前端当停留在查看验证码的页面时，前端会每隔一段时间请求一个 url，这个 url 每请求一次，就会重新生成一个验证码并返回
- 另外起一个线程，每隔一段时间给活动重新生成一个验证码

大家有什么别的思路吗 @taoky @NeapolitanIcecream

**Comment by taoky** [comment]
> 大家对通过验证码签到的方式有什么建议吗。我按照前期讨论，目前有两个思路：
> 
> * 前端当停留在查看验证码的页面时，前端会每隔一段时间请求一个 url，这个 url 每请求一次，就会重新生成一个验证码并返回
> * 另外起一个线程，每隔一段时间给活动重新生成一个验证码
> 
> 大家有什么别的思路吗 @taoky @NeapolitanIcecream

第二种方案是打算用 Websocket?

**Comment by kaleid-liner** [comment]
> 第二种方案是打算用 Websocket?

是的

**Comment by taoky** [comment]
> > 第二种方案是打算用 Websocket?
> 
> 是的

我觉得可以试一下 Websocket ~~（这样最后答辩也有新东西可以说）~~

当然如果 ws 的话工作量会大一点，最后实在不行就 fallback 到第一种更容易实现的版本吧……

**Comment by kaleid-liner** [comment]
> 我觉得可以试一下 Websocket （这样最后答辩也有新东西可以说）

OK，那我就用这种方式（只不过前端工作量也会稍微大一些）

**Comment by NeapolitanIcecream** [comment]
> 大家对通过验证码签到的方式有什么建议吗。我按照前期讨论，目前有两个思路：
> 
> * 前端当停留在查看验证码的页面时，前端会每隔一段时间请求一个 url，这个 url 每请求一次，就会重新生成一个验证码并返回
> * 另外起一个线程，每隔一段时间给活动重新生成一个验证码
> 
> 大家有什么别的思路吗 @taoky @NeapolitanIcecream

我觉得种子 + 时间戳在前端生成验证码就好。

后端存种子就好。

**Comment by kaleid-liner** [comment]
在 d82541b3c 中基本完成了功能。使用 @taoky 提示的 [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm) 进行时间相关的 OTP 生成。

TODO:
- [ ] 关于前后端时间的同步。从哪里获取统一的时间戳？

**Comment by NeapolitanIcecream** [comment]
我想活动签到的情景不需要精度特别高的授时方案，NTP + 任何常用的 NTP 服务器就可以。

我建议在 `settings.py` 里增加 NTP 服务器的配置。考虑到这一情景主要发生在校园网下，可以默认为 `ntp.ntsc.ac.cn`。

**Comment by kaleid-liner** [comment]
> 我想活动签到的情景不需要精度特别高的授时方案，NTP + 任何常用的 NTP 服务器就可以。
> 
> 我建议在 `settings.py` 里增加 NTP 服务器的配置。考虑到这一情景主要发生在校园网下，可以默认为 `ntp.ntsc.ac.cn`。

嗯，我就这样做
