### ISSUE TITLE
创建活动（涉及到的通知等参见用户故事）

### ISSUE THREAD

**Issue by taoky** [Community-Member-Management-System/CMMS-Backend#4]

**Comment by kaleid-liner** [comment]
TODO:
- [ ] 创建活动时的通知 description 内容？
- [ ] 用户故事中创建活动时的通知类型（通知哪些用户）在目前的 notice 框架下实现比较复杂，目前只实现基础的通知（通知所有成员）
- [ ] 活动相册相关的处理

**Comment by kaleid-liner** [comment]
由于目前只完成了基础功能，在添加活动相册后相关内容仍需更新，所以先 reopen 了

**Comment by NeapolitanIcecream** [comment]
> * [ ]  创建活动时的通知 description 内容？

社团活动通知类型的通知的 `description` 域被设计为传递活动名称或活动名称和活动简介等信息。我想你可以自由设计其格式，只要在 notice README 里告诉前端如何解析就行。

我个人推荐活动名称 + URL。

> * [ ]  用户故事中创建活动时的通知类型（通知哪些用户）在目前的 notice 框架下实现比较复杂，目前只实现基础的通知（通知所有成员）

看上去为活动模型增加一个通知类型的域就可以了。邮件通知可以先注释一个空接口。

用户故事里的邮件通知看上去很容易被滥用，不论是使用第三方邮件列表服务还是平台管理员自己设置一些账号。有点难以下手。我觉得要求社团提供邮箱账号是不错的方案。 @taoky 你觉得怎么样？

**Comment by taoky** [comment]
> 用户故事里的邮件通知看上去很容易被滥用，不论是使用第三方邮件列表服务还是平台管理员自己设置一些账号。有点难以下手。我觉得要求社团提供邮箱账号是不错的方案。 @taoky 你觉得怎么样？

滥用是指社团管理员会给成员发送垃圾邮件吗 emmmm，还是说成员的 email 可能会乱填？如果要求社团管理员提供一个邮件列表的地址，让成员自己去 subscribe，后端只发邮件到邮件列表的话应该也可以。

**Comment by NeapolitanIcecream** [comment]
> > 用户故事里的邮件通知看上去很容易被滥用，不论是使用第三方邮件列表服务还是平台管理员自己设置一些账号。有点难以下手。我觉得要求社团提供邮箱账号是不错的方案。 @taoky 你觉得怎么样？
> 
> 滥用是指社团管理员会给成员发送垃圾邮件吗 emmmm，还是说成员的 email 可能会乱填？如果要求社团管理员提供一个邮件列表的地址，让成员自己去 subscribe，后端只发邮件到邮件列表的话应该也可以。

社团管理员可以这样滥用：修改自己的 email 从而以平台提供的邮箱的名义向任意地址发送任意邮件。要求社团管理员提供一个邮件列表地址的话，也有这个问题。除非把它也加入平台管理员的审核项目。

**Comment by NeapolitanIcecream** [comment]
> > > 用户故事里的邮件通知看上去很容易被滥用，不论是使用第三方邮件列表服务还是平台管理员自己设置一些账号。有点难以下手。我觉得要求社团提供邮箱账号是不错的方案。 @taoky 你觉得怎么样？
> > 
> > 
> > 滥用是指社团管理员会给成员发送垃圾邮件吗 emmmm，还是说成员的 email 可能会乱填？如果要求社团管理员提供一个邮件列表的地址，让成员自己去 subscribe，后端只发邮件到邮件列表的话应该也可以。
> 
> 社团管理员可以这样滥用：修改自己的 email 从而以平台提供的邮箱的名义向任意地址发送任意邮件。要求社团管理员提供一个邮件列表地址的话，也有这个问题。除非把它也加入平台管理员的审核项目。

啊，基于第一点，我觉得我们有一件很常见的事情没有做，那就是验证邮箱。如果用户确实 have access to 邮箱，那么这件事我们就不用管了。
