### ISSUE TITLE
加入社团，也涉及到各种给社团管理员的通知，审核过程

### ISSUE THREAD

**Issue by taoky** [Community-Member-Management-System/CMMS-Backend#6]

**Comment by taoky** [comment]
目前进展：

可以加入社团，社团管理员可以审核。通知未实现。

**Comment by NeapolitanIcecream** [comment]
现在加入社团可以不经过审核。

建议在 community model 下开一个一对多维护待审核列表。

审核通知被期望在新成员申请加入社团、即用户被加入待审核列表时发生，因此不得不推迟直到该部分完成。

**Comment by taoky** [comment]
> 现在加入社团可以不经过审核。

Emmmm，目前的实现是在 Membership 这个表里面加了一个 valid 的 `BoolField` 字段，但是显示社团成员的接口还没改（会显示所有的成员）。审核的功能目前是筛选出所有 `valid = False` 来实现的。

**Comment by NeapolitanIcecream** [comment]
> > 现在加入社团可以不经过审核。
> 
> Emmmm，目前的实现是在 Membership 这个表里面加了一个 valid 的 `BoolField` 字段，但是显示社团成员的接口还没改（会显示所有的成员）。审核的功能目前是筛选出所有 `valid = False` 来实现的。

我明白了。

**Comment by taoky** [comment]
> > 现在加入社团可以不经过审核。
> 
> Emmmm，目前的实现是在 Membership 这个表里面加了一个 valid 的 `BoolField` 字段，但是显示社团成员的接口还没改（会显示所有的成员）。审核的功能目前是筛选出所有 `valid = False` 来实现的。

显示成员的接口改好了，现在只会显示 valid 的成员。

**Comment by NeapolitanIcecream** [comment]
通知已经支持。

暂时没有传 `description` 字段。它本来被设计为「申请理由」或者「附加信息」之类的在这种场景可能用到的信息。

你觉得我们还需要它吗？如果要的话，有可能要改一下 `CommunityJoinSerializer`。

**Comment by taoky** [comment]
> 通知已经支持。
> 
> 暂时没有传 `description` 字段。它本来被设计为「申请理由」或者「附加信息」之类的在这种场景可能用到的信息。
> 
> 你觉得我们还需要它吗？如果要的话，有可能要改一下 `CommunityJoinSerializer`。

附加信息我觉得可以之后再说。另外申请通过/被拒绝应该也要一个通知？

**Comment by NeapolitanIcecream** [comment]
> > 通知已经支持。
> > 暂时没有传 `description` 字段。它本来被设计为「申请理由」或者「附加信息」之类的在这种场景可能用到的信息。
> > 你觉得我们还需要它吗？如果要的话，有可能要改一下 `CommunityJoinSerializer`。
> 
> 附加信息我觉得可以之后再说。另外申请通过/被拒绝应该也要一个通知？

已实现和测试。

同样的，以后如果需要，还可以在 description 域加上附加消息。
